post http://localhost:7500/api/auth/signup
Content-Type: application/json

{
  "email": "abc@123.com",
  "username": "abc123",
  "password": "123456",
  "firstname": "Mr. Abc",
  "lastname": "Def",
  "address": "No. 123 Abc Road",
  "lga": "Lazy Dog L.G.A",
  "state": "Some State",
  "occupation": "general repairer",
  "phone": "0-123-456-7"
}

###
post http://localhost:7500/api/auth/login
Content-Type: application/json


{
  
}